name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: setup Python 3.19
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirement.txt

      - name: Test with PyTest
        run: |
          python -m pytest --cov=catchmet.models tests/test_model.py